triggerAtDistanceBelow = 32
damageOnFall = 19
fallingHeight = 256
preventDeath = false
triggerInOverworld = false
triggerInNether = false
triggerInEnd = true
disableVanillaAntiCheatWhileFalling = true
dimensionAllowList = []
dimensionDenyList = []
