name = "AwesomeModPack"
author = "ShkSchneider"
version = "0.9.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fef5f972db6be32703f13cc8b3cf4e87338164bcd036211fa59ab48b42ebba8a"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
