name = "AwesomeModPack"
author = "ShkSchneider"
version = "0.9.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "165cf48acf888e92a4e96810352c551bd2ad4cb77f1ce0b93427dc2ad635ca84"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
