name = "AwesomeModPack"
author = "ShkSchneider"
version = "0.9.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd94946da7836fe155bbd17ea9537a83423a5f432191f8c3eff48fa362490394"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
