name = "AwesomeModPack"
author = "ShkSchneider"
version = "0.9.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "236cc298ab155ad1ff7f505d5fd00f1beb22e251ee690232c161e16858227ace"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
