name = "AwesomeModPack"
author = "ShkSchneider"
version = "0.9.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "389ab2e5b2df914aa0deb1fed9175782b6203788e24319118dcf944f388dab8a"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
