name = "AwesomeModPack"
author = "ShkSchneider"
version = "0.9.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40dfa6ece47e90333c4e2d71bd509e8b94f5a8d733abffda8027389c1a1f7920"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
