name = "AwesomeModPack"
author = "ShkSchneider"
version = "0.9.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e630cb77e17e1090f407f54c86883b13d52a8f92f379d26f2ed2528a2affb0f"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
