name = "AwesomeModPack"
author = "ShkSchneider"
version = "0.9.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "527e4450c02dd7d61e8ff51a4a02f8c7d0d28eb45f41bbee2f6084158ae7bdb3"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
