name = "AwesomeModPack"
author = "ShkSchneider"
version = "0.9.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f5e86821085db9290f1395e691000359b2c4569cc2b40faecb92abb2cd6e637"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
