name = "AwesomeModPack"
author = "ShkSchneider"
version = "0.9.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e14a94bca05ac521329074519adf8dd1d7e816e4348dab1a7104f2b34d3c3b1"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
