name = "AwesomeModPack"
author = "ShkSchneider"
version = "0.9.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6383a0c23645318900a1c3c8585edfc194c98dfd544542b2d3419fddd426bd0"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
