name = "AwesomeModPack"
author = "ShkSchneider"
version = "0.9.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2546917c275cccddacd2c6aced8e66df8b26b070a540de18e30ea7d1a743b71"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
