name = "AwesomeModPack"
author = "ShkSchneider"
version = "0.9.17"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "698ae65a7b079bbc8366c9c6a6d6d885079897bde7b00671a0c1bdfc23207684"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
