name = "AwesomeModPack"
author = "ShkSchneider"
version = "0.9.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8dc0e67a14ab10e8a0ba389cb1e40682de146b3d56f69181ee0c2e9ced2f6048"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
