name: build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: gradlew
        uses: gradle/wrapper-validation-action@v1
      - name: jdk
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build --stacktrace
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/libs/*[0-9].jar
